version: "3.8"

x-env: &env
  TERM: "xterm-256color"
  ENV: DEV
  DB_URL: postgres://postgres:postgres@postgres:5432/postgres

services:
  postgres:
    hostname: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  python_fastapi:
    tty: true
    build:
      context: ./python/fastapi
      dockerfile: ./.docker/images/python/Dockerfile
#    command: uvicorn app:app --host=0.0.0.0 --port 8000 --reload --http h11 --loop uvloop --log-level info
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      <<: *env
    ports:
      - "8000:8000"
  python_flask:
    tty: true
    build:
      context: ./python/flask
      dockerfile: ./.docker/images/python/Dockerfile
#    command: uvicorn app:app --host=0.0.0.0 --port 8000 --reload --http h11 --loop uvloop --log-level info
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      <<: *env
    ports:
      - "8001:8000"