version: '3'

vars:
  REGISTRY: "localhost:5005"

tasks:
  build_fastapi:
    cmds:
      - docker build -f ./.docker/images/fastapi/Dockerfile -t localhost:5005/fastapi-app .
  build_flask:
    cmds:
      - docker build -f ./.docker/images/flask/Dockerfile -t localhost:5005/flask-app .
  build_quarkus:
    cmds:
      - docker build --no-cache -f ./.docker/images/quarkus/Dockerfile -t localhost:5005/quarkus-app .
  build_micronaut:
    cmds:
      - docker build --no-cache -f ./.docker/images/micronaut/Dockerfile -t localhost:5005/micronaut-app .
  run-tests:
    cmds:
      - docker-compose run k6 run {{.CLI_ARGS}}
  deploy:
    cmds:
      - kustomize build --load-restrictor LoadRestrictionsNone ./manifests/overlays/{{.CLI_ARGS}} | kubectl apply -f -
  test:
    cmds:
      - kubectl delete jobs/k6-job || true
      - kustomize build --load-restrictor LoadRestrictionsNone ./manifests/overlays/scenarios/{{.CLI_ARGS}} | kubectl apply -f -