micronaut:
  application:
    name: mgrQuarkus
  server:
    port: 8000
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
