apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-server
        app.kubernetes.io/part-of: testing
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          envFrom:
            - configMapRef:
                name: grafana-cm
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards
              name: dashboard-vm
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasource-vm
            - mountPath: /var/lib/grafana/dashboards
              name: results-vm
      volumes:
        - name: dashboard-vm
          configMap:
            name: dashboard-cm
        - name: datasource-vm
          configMap:
            name: datasource-cm
        - name: results-vm
          configMap:
            name: results-cm
