apiVersion: batch/v1
kind: Job
metadata:
  labels:
    postgres.kubernetes.io/name: k6-job
    postgres.kubernetes.io/component: job
  name: k6-job
  namespace: test
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k6
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: testing
    spec:
      containers:
        - name: k6
          image: loadimpact/k6:latest
          command:
            - /bin/sh
            - -c
          args:
            - k6 run /scenarios/script.js
          envFrom:
            - configMapRef:
                name: k6-cm
          volumeMounts:
            - mountPath: /scenarios
              name: scenario-volume
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - app-server
      volumes:
        - name: scenario-volume
          configMap:
            name: scenario-cm

      restartPolicy: Never