apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgres-server
    app.kubernetes.io/component: server
  name: postgres-server
  namespace: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-server
        app.kubernetes.io/part-of: testing
    spec:
      containers:
        - image: postgres:12
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres-cm
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5432
              name: tcp
              protocol: TCP
