apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-server
    app.kubernetes.io/component: server
  name: postgres-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres-server
