apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app-server
    app.kubernetes.io/component: server
  name: app-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-server
    spec:
      containers:
        - image: app
          name: app
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            runAsGroup: 1000