apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app-server
    app.kubernetes.io/component: server
  name: app-server
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/part-of
                    operator: In
                    values:
                      - testing
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - app-server
      containers:
        - image: app
          name: app
          resources:
            requests:
              memory: "500Mi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "4"
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /s1
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 30
            initialDelaySeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: http
              path: /s1
            failureThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            runAsGroup: 1000
          imagePullPolicy: Always