apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-server
    app.kubernetes.io/component: server
  name: app-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: app-server
